# Generated by Django 4.0.2 on 2022-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketalgo', '0005_alter_purchase_price_mkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_mkt',
            field=models.FloatField(default=0.944185),
        ),
    ]
