# Generated by Django 4.0.2 on 2022-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketalgo', '0006_alter_purchase_price_mkt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price_mkt',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_price',
            field=models.FloatField(default=0),
        ),
    ]
