# Generated by Django 4.0.2 on 2022-02-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketalgo', '0007_remove_purchase_price_mkt_remove_purchase_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_principal', models.CharField(max_length=150)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='pics/%y/%m/%d/')),
                ('action_name', models.CharField(max_length=50)),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
