# Generated by Django 4.0.2 on 2022-02-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_n_algo_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='n_ALGO_coin',
            field=models.FloatField(default=1.969548),
        ),
    ]
