# Generated by Django 4.0.2 on 2022-02-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_n_algo_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='n_ALGO_coin',
            field=models.FloatField(default=4.44845),
        ),
    ]
