# Generated by Django 4.0.2 on 2022-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_n_algo_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ALGO_Wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='n_ALGO_coin',
            field=models.FloatField(default=0.886022),
        ),
    ]
