# Generated by Django 4.0.2 on 2022-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_algo_wallet_alter_profile_n_algo_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='n_ALGO_coin',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ALGO_Wallet',
            field=models.FloatField(default=5.385486),
        ),
    ]
