# Generated by Django 4.0.2 on 2022-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_options_alter_profile_algo_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ALGO_Wallet',
            field=models.FloatField(default=2),
        ),
    ]
