# Generated by Django 4.0.2 on 2022-02-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_algo_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='purchased_coin',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ALGO_Wallet',
            field=models.FloatField(default=9),
        ),
    ]
