# Generated by Django 4.0.2 on 2022-03-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_purchased_coin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ALGO_Pending_Wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='USD_Pending_Wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ALGO_Wallet',
            field=models.FloatField(default=6),
        ),
    ]
