# Generated by Django 4.0.2 on 2022-03-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertransaction', '0002_order_name_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_order',
        ),
    ]
